#!/usr/bin/env bash
# Render a ready-to-paste [Extension Submission] issue for github/spec-kit as
# a markdown document. The release pipeline uploads it as an artifact so a
# maintainer can file the issue manually — automatic `gh issue create` against
# the upstream repo proved unreliable.
#
# Flow:
#   1. Look up the current entry in upstream catalog.community.json.
#      - present → title: "[Extension]: Update <name> to vX.Y.Z"
#      - absent  → title: "[Extension]: Add <name>"
#   2. Render manual steps + the issue title + the issue body from catalog.json.
#   3. Write the document to OUTPUT_FILE.
#
# Env:
#   UPSTREAM_REPO  Defaults to github/spec-kit.
#   OUTPUT_FILE    Where to write the document. Defaults to
#                  "upstream-catalog-issue-v<version>.md" in the cwd.
#
# Usage:
#   submit-catalog-update.sh <version> [release_type] [git_tag]
#   release_type defaults to "release"; git_tag defaults to "v<version>".

set -euo pipefail

VERSION="${1:-}"
RELEASE_TYPE="${2:-release}"
GIT_TAG="${3:-v${VERSION}}"
UPSTREAM_REPO="${UPSTREAM_REPO:-github/spec-kit}"

if [ -z "$VERSION" ]; then
    echo "Usage: $0 <version> [release_type] [git_tag]" >&2
    exit 1
fi

if [ -z "${GITHUB_REPOSITORY:-}" ]; then
    echo "[submit-catalog-update] FAIL: GITHUB_REPOSITORY not set" >&2
    exit 1
fi

DOWNLOAD_URL="https://github.com/${GITHUB_REPOSITORY}/releases/download/${GIT_TAG}/product-${VERSION}.zip"
OUTPUT_FILE="${OUTPUT_FILE:-upstream-catalog-issue-v${VERSION}.md}"

for tool in jq curl; do
    if ! command -v "$tool" >/dev/null 2>&1; then
        echo "[submit-catalog-update] FAIL: $tool is required" >&2
        exit 1
    fi
done

if [ ! -f catalog.json ]; then
    echo "[submit-catalog-update] FAIL: catalog.json not found" >&2
    exit 1
fi

EXT_ID=$(jq -r '.id' catalog.json)
EXT_NAME=$(jq -r '.name' catalog.json)
EXT_DESC=$(jq -r '.description' catalog.json)
EXT_AUTHOR=$(jq -r '.author' catalog.json)
EXT_REPO=$(jq -r '.repository' catalog.json)
EXT_HOMEPAGE=$(jq -r '.homepage // ""' catalog.json)
EXT_DOCS=$(jq -r '.documentation // ""' catalog.json)
EXT_CHANGELOG=$(jq -r '.changelog // ""' catalog.json)
EXT_LICENSE=$(jq -r '.license' catalog.json)
EXT_SPECKIT=$(jq -r '.requires.speckit_version' catalog.json)
EXT_CMDS=$(jq -r '.provides.commands' catalog.json)
EXT_HOOKS=$(jq -r '.provides.hooks' catalog.json)
EXT_TAGS=$(jq -r '.tags | join(", ")' catalog.json)

CATALOG_URL="https://raw.githubusercontent.com/${UPSTREAM_REPO}/main/extensions/catalog.community.json"
HAS_ENTRY=$(curl -fsSL "$CATALOG_URL" | jq -r --arg id "$EXT_ID" '.extensions[$id] // empty' || echo "")

if [ -n "$HAS_ENTRY" ]; then
    ACTION="Update"
    TITLE="[Extension]: Update ${EXT_NAME} to v${VERSION}"
else
    ACTION="Add"
    TITLE="[Extension]: Add ${EXT_NAME}"
fi

NEW_ISSUE_URL="https://github.com/${UPSTREAM_REPO}/issues/new/choose"
TITLE_QUERY="${TITLE// /+}"

PROPOSED_ENTRY=$(jq --arg v "$VERSION" --arg u "$DOWNLOAD_URL" \
    '{($id): (. + {version: $v, download_url: $u, verified: false, downloads: 0, stars: 0})}
     | .[$id] |= del(.created_at, .updated_at)' \
    --arg id "$EXT_ID" catalog.json)

cat >"$OUTPUT_FILE" <<EOF
# Upstream catalog issue — ${ACTION} ${EXT_NAME} v${VERSION}

> Generated by the \`${EXT_REPO}\` release pipeline. File this issue manually
> on the upstream Spec Kit repo.

## How to file this issue

1. Open the new-issue page: ${NEW_ISSUE_URL}
2. Pick the **Extension Submission** template.
3. Set the issue **title** to (copy exactly):

   \`${TITLE}\`

4. Fill each form field with the matching value from the **Issue body** section
   below (each \`###\` heading maps to one form field).
5. Before submitting, check there is no open issue with the same title at
   https://github.com/${UPSTREAM_REPO}/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+${TITLE_QUERY}

---

## Issue body

> **Submission** from \`${EXT_REPO}\` release pipeline. ${ACTION} request for \`${EXT_ID}\` v${VERSION}.

### Extension ID

${EXT_ID}

### Extension Name

${EXT_NAME}

### Version

${VERSION}

### Description

${EXT_DESC}

### Author

${EXT_AUTHOR}

### Repository URL

${EXT_REPO}

### Download URL

${DOWNLOAD_URL}

### License

${EXT_LICENSE}

### Homepage (optional)

${EXT_HOMEPAGE}

### Documentation URL (optional)

${EXT_DOCS}

### Changelog URL (optional)

${EXT_CHANGELOG}

### Required Spec Kit Version

${EXT_SPECKIT}

### Number of Commands

${EXT_CMDS}

### Number of Hooks (optional)

${EXT_HOOKS}

### Tags

${EXT_TAGS}

### Release type

\`${RELEASE_TYPE}\`

### Testing Checklist

- [x] Extension installs successfully via download URL
- [x] All commands execute without errors
- [x] Documentation is complete and accurate
- [x] No security vulnerabilities identified
- [x] Tested on at least one real project (CI release pipeline)

### Submission Requirements

- [x] Valid \`extension.yml\` manifest included
- [x] README.md with installation and usage instructions
- [x] LICENSE file included
- [x] GitHub release created with version tag
- [x] All command files exist and are properly formatted
- [x] Extension ID follows naming conventions (lowercase-with-hyphens)

### Proposed Catalog Entry

\`\`\`json
${PROPOSED_ENTRY}
\`\`\`
EOF

echo "[submit-catalog-update] OK: wrote ${ACTION} v${VERSION} document to ${OUTPUT_FILE}"
